build:
  parallel: true

artifacts:
  - path: MyDatabase\bin\debug\MyDatabase.dacpac
    name: MyDatabase

deploy:
  - provider: SqlDatabase
    artifact: MyDatabase
    connection_string:
      secure: r5FHTTIfknKXrvMwsfqC/swG2n81GGc0PruruI5DVSMAocqz+E23+fTQQS3UO0FSkrGygtgdIGZOCV3ZEHs8vclEa5JZ14LDeaHdZQTQJ8V7CQOYM+BA2qiJ2+vu6T7crpkaYmnOhLAS8dgkFA3dRFPURyIGhdZP9pqJPJPIBgiGOFnSRnvPsFP+I/haV4gn52oH6/EvSZyINz7oDduwUTI9X3UeIw9cAR8DQKtf/Hk=
    script_database_options: false
    drop_objects_not_in_source: true
    #backup_database_before_changes: true
    ignore_file_and_log_file_path: true
