services:
  - mssql2012sp1

artifacts:
  - path: MyDatabase\bin\debug\MyDatabase.dacpac
    name: MyDatabase

deploy:
  - provider: SqlDatabase
    artifact: MyDatabase
    connection_string: 'Server=(local)\SQL2012SP1;Database=test102;User ID=sa;Password=Password12!'
    drop_objects_not_in_source: true
    backup_database_before_changes: true
