artifacts:
  - path: MyDatabase\bin\debug\MyDatabase.dacpac
    name: MyDatabase

deploy:
- provider: SqlDatabase
  artifact: MyDatabase
  connection_string:
    secure: f/YeQsWruv6i3ls/WBxvMotaiNqZViJkXKWV8GZGnRW0mUGPI51cZw6nimdh9VlKO3lUKqZXbjUIw8ptqBfJN1r7XIsMPea09P1iQ3P/XzwkIHmTRVBUk9cBodylHbAdB9UsqzuB2Q4RFm1SGQarX2kkESlVcdoDpGBBuTnx0z1J1/iwbfN0d7t27HdgJ1uKmQS3YQNrdqKbpCvuyimvj/7VqOFdHYLCKwhsX6zN6F8=
  script_database_options: false
  create_new_database: false
  block_on_possible_data_loss: true
  deploy_database_in_single_user_mode: false
  backup_database_before_changes: false
  drop_objects_not_in_source: false
  no_alter_statements_to_change_clr_types: false
  allow_drop_blocking_assemblies: false
  allow_incompatible_platform: false
  comment_out_set_var_declarations: false
  compare_using_target_collation: false
  disable_and_reenable_ddl_triggers: true
  do_not_alter_change_data_capture_objects: true
  do_not_alter_replicated_objects: true
  drop_constraints_not_in_source: true
  drop_dml_triggers_not_in_source: true
  drop_extended_properties_not_in_source: true
  drop_indexes_not_in_source: true
  drop_permissions_not_in_source: false
  drop_role_members_not_in_source: false
  generate_smart_defaults: false
  ignore_ansi_nulls: true
  ignore_authorizer: false
  ignore_column_collation: false
  ignore_comments: false
  ignore_cryptographic_provider_file_path: true
  ignore_ddl_trigger_order: false
  ignore_ddl_trigger_state: false
  ignore_default_schema: false
  ignore_dml_trigger_order: false
  ignore_dml_trigger_state: false
  ignore_extended_properties: true
  ignore_file_and_log_file_path: true
  ignore_filegroup_placement: true
  ignore_file_size: true
  ignore_fill_factor: true
  ignore_full_text_catalog_file_path: true
  ignore_identity_seed: false
  ignore_increment: false
  ignore_index_options: false
  ignore_index_padding: true
  ignore_keyword_casing: true
  ignore_lock_hints_on_indexes: false
  ignore_login_sids: true
  ignore_not_for_replication: false
  ignore_object_placement_on_partition_scheme: true
  ignore_partition_schemes: false
  ignore_permissions: false
  ignore_quoted_identifiers: true
  ignore_role_membership: false
  ignore_route_lifetime: true
  ignore_semicolon_between_statements: true
  ignore_table_options: false
  ignore_user_settings_objects: false
  ignore_whitespace: true
  ignore_with_nocheck_on_check_constraints: false
  ignore_with_nocheck_on_foreign_keys: false
  include_composite_objects: true
  include_transactional_scripts: false
  populate_files_on_file_groups: false
  script_database_collation: false
  script_database_compatibility: false
  script_deploy_state_checks: false
  script_file_size: false
  script_new_constraint_validation: true
  script_refresh_module: true
  treat_verification_errors_as_warnings: false
  unmodifiable_object_warnings: true
  verify_collation_compatibility: true
  verify_deployment: true