artifacts:
  - path: MyDatabase\bin\debug\MyDatabase.dacpac
    name: MyDatabase

deploy:
  - provider: SqlDatabase
    artifact: MyDatabase
    connection_string:
      secure: f/YeQsWruv6i3ls/WBxvMqyzEc9hoXzgnIWn4bbEDfO3q+lDOXGRyt4QV5NIgBi+F7MXwxr8yWiPyJ3/PlZXjyC6G21QocFIGIgTiEX/2IQRg5BPe/y86iivLgoOv1TVS5YoHpq5G/QW5WCAd5VbQjJPFGo6j+OLPcdUfM2COgd24awDmbCCYOw4Sny0rQoLsf79Lpjr6FinPkl/GHI14pCoKBQHulNdfnWAzZFYBzBFZngfcaskpoEbX/cuF3HD
    drop_objects_not_in_source: true
    backup_database_before_changes: true
