environment:
  TEST_CONNECTION_STRING: Server=(local)\SQL2008R2SP2;Database=master;User ID=sa;Password=Password12!

services:
  - mssql2008r2sp2

build: off

# make sure tables have been created
test_script:
  - sqlcmd -S "(local)\SQL2008R2SP2" -U "sa" -P "Password12!" -i "test.sql" -d "master" -o AccountServerSetup.out
