environment:
  TEST_CONNECTION_STRING: Server=(local)\SQL2008R2SP2;Database=master;User ID=sa;Password=Password12!

services:
  - mssql2008r2sp2

build: off

# make sure tables have been created
test_script:
  - ps: |
        $conn = New-Object System.Data.SqlClient.SqlConnection
        $conn.ConnectionString = $env:TEST_CONNECTION_STRING
        $conn.Open()
        $cmd = New-Object System.Data.SqlClient.SqlCommand("SELECT * FROM information_schema.tables", $conn)
        $reader = $cmd.ExecuteReader()
        while($reader.Read())
        {
          Write-Host "Table: $($reader["table_name"])"
        }
        $conn.Close()
